## You can use this file to create a conda environment for this pipeline.
## See docs: https://github.com/crickbabs/BABS-MNASeqPE/blob/master/docs/config.md

name: BABS-MNASeqPE-1.0
channels:
    - defaults
    - conda-forge
    - bioconda
    - imperial-college-research-computing
dependencies:
    - conda-forge::ncurses=5.9                 ## Documented conflict between R and SAMTools. See https://github.com/bioconda/bioconda-recipes/issues/1644
    - samtools=1.7
    - fastqc=0.11.7
    - fastq-screen=0.11.3
    - cutadapt=1.16
    - bwa=0.7.17
    - picard=2.18.7
    - bamtools=2.5.1
    - pysam=0.14.0
    - bedtools=2.27.1
    - ucsc-wigtobigwig=366
    - multiqc=1.5
    - r=3.4.1
    - danpos=2.2.2
